name: Publish Contract Addresses

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run fetch

      - name: Check for changes
        id: changes
        run: |
          git add data/
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish if changed
        if: steps.changes.outputs.changed == 'true'
        run: |
          VERSION="1.0.$(date +%Y%m%d%H%M%S)"
          npm version $VERSION --no-git-tag-version
          
          npm run build
          npm publish --access public
          
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update addresses v$VERSION"
          git push
      
